<a href="https://colab.research.google.com/github/emirhneks/YapayZekaVeMakineOgrenmesi11/blob/main/numpy_1243.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1) (10,15,30,45,60) değerlerine sahip numpy dizisi oluştur

In [2]:
result = np.array([10,15,30,45,60])
print(result)

[10 15 30 45 60]


# 2) (5-15) arasındaki sayılarla numpy dizisi oluştur

In [3]:
result = np.arange(5,15)
print(result)

[ 5  6  7  8  9 10 11 12 13 14]


# 3) (50-100) arasında 5'er 5'er artacak numpy dizisi oluştur

In [4]:
result = np.arange(50,100,5)
print(result)

[50 55 60 65 70 75 80 85 90 95]


# 4) 10 elemanlı sıfırlardan oluşan bir dizi oluştur

In [5]:
result = np.zeros(10)
print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 5) 10 elemanlı birlerden oluşan bir dizi oluştur

In [6]:
result = np.ones(10)
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# 6) (0-100) arasında eşit aralıklı 5 sayı üret

In [7]:
result = np.linspace(0,100,5)
print(result)

[  0.  25.  50.  75. 100.]


# 7) (10-30) arasında rastgele 5 tane tam sayı üret

In [8]:
result = np.random.randint(10,30,5)
print(result)

[24 28 11 11 10]


# 8) [-1 ile 1] arasında 10 adet sayı üret

In [9]:
result = np.random.rand(10)
print(result)

[0.48033738 0.18618491 0.6501616  0.46191494 0.68292268 0.03514537
 0.21043574 0.14201085 0.00788641 0.49729539]


# 9) (3x5) boyutlarında (10-50) arasında rastgele bir matris oluştur

In [10]:
result = np.random.randint(10,50,15).reshape(3,5)
print(result)

[[17 37 31 42 45]
 [46 34 11 15 23]
 [34 33 47 22 47]]


# 10) Üretilen matrisin satır ve sütun sayıları toplamını hesapla

In [11]:
matris = np.random.randint(10,50,15).reshape(3,5)
rowTotal = matris.sum(axis=1)
colTotal = matris.sum(axis=0)
print(matris)
print(rowTotal)
print(colTotal)

[[28 23 14 34 10]
 [20 21 44 22 31]
 [35 21 42 27 45]]
[109 138 170]
[ 83  65 100  83  86]


# 11) Üretilen matrisin en büyük, en küçük ve ortalaması nedir

In [12]:
matris = np.random.randint(10,50,15).reshape(3,5)
max = matris.max()
min = matris.min()
mean = matris.mean()
print(matris)
print(max)
print(min)
print(mean)

[[37 18 12 18 11]
 [17 44 34 17 29]
 [29 21 30 25 32]]
44
11
24.933333333333334


# 12) Üretilen matrisin en büyük değerinin indeksi kaçtır

In [13]:
matris = np.random.randint(10,50,15).reshape(3,5)
result = matris.argmax()
print(matris)
print(result)

[[48 49 36 30 35]
 [43 17 24 16 30]
 [27 15 48 40 49]]
1


# 13) (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seç

In [14]:
arr = np.arange(10,20)
result = arr[:3]
print(arr)
print(result)

[10 11 12 13 14 15 16 17 18 19]
[10 11 12]


# 14) Üretilen dizinin elemanlarını tersten yaz

In [15]:
arr = np.arange(10,20)
result = arr[::-1]
print(arr)
print(result)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


# 15) Üretilen matrisin ilk satırını seç

In [16]:
matris = np.random.randint(10,50,15).reshape(3,5)
result = matris[0]
print(matris)
print(result)

[[30 46 45 26 20]
 [21 27 26 36 33]
 [31 43 48 25 24]]
[30 46 45 26 20]


# 16) Üretilen matrisin 2. satır 3. sütundaki elemanı nedir

In [17]:
matris = np.random.randint(10,50,15).reshape(3,5)
result = matris[1,2]
print(matris)
print(result)

[[43 43 18 39 38]
 [30 48 23 44 25]
 [11 39 30 30 29]]
23


# 17) Üretilen matrisin tüm satırlarındaki ilk elemanı seç

In [18]:
matris = np.random.randint(10,50,15).reshape(3,5)
result = matris[:,0]
print(matris)
print(result)

[[20 38 36 47 15]
 [28 33 36 28 28]
 [13 34 27 10 49]]
[20 28 13]


# 18) Üretilen matrisin her bir elemanının karesini al

In [19]:
matris = np.random.randint(10,50,15).reshape(3,5)
result = matris ** 2
print(matris)
print(result)

[[25 46 42 38 35]
 [29 45 49 39 47]
 [20 43 28 45 36]]
[[ 625 2116 1764 1444 1225]
 [ 841 2025 2401 1521 2209]
 [ 400 1849  784 2025 1296]]


# 19) Üretilen matris elemanlarının hangileri pozitif çift sayıdır

In [20]:
matris = np.random.randint(10,50,15).reshape(3,5)
ciftler = matris[matris % 2 == 0]
result = ciftler[ciftler > 0]
print(matris)
print(result)

[[12 20 36 12 24]
 [31 23 17 16 43]
 [15 18 26 46 32]]
[12 20 36 12 24 16 18 26 46 32]
